### PR TITLE
Update gnirts.js

### PR DESCRIPTION
**Pull request by LoicLemerlus**
added the possibility to catch if there is a ; after the text  which browserify add by default

### CODE REVIEW

**Comment by anseki** [comment]
Hi @LoicLemerlus, thank you for the PR.
Please, more details and cases about that.

**Comment by LoicLemerlus** [comment]
Hi @anseki 
The problem is the following:

When trying to hide text with

```
const ID = /* @mangle */ 'some hash' /* @/mangle */
```

this works fine, however if you use a build tool like browserify it will modify the line into:

```
const ID = /* @mangle */ 'some hash'; /* @/mangle */
```

this cause gnirts to through the following error:

> Error: Invalid directive: 'some hash';
> at ....../node_modules/gnirts/lib/gnirts.js:209:13

modifying the regex from
`reLiteral = /^\s*(\+\s*)?(['"][\s\S]*['"])(\s*\+)?\s*$/`
to
`reLiteral = /^\s*(\+\s*)?(['"][\s\S]*['"]);?(\s*\+)?\s*$/`

allows to still match the text if there is a ; after it

I also added ' ?' just in case another build tool would add a white space as well

Thank you,
Loic

**Comment by anseki** [comment]
Thank you for the explanation.

Unfortunately your patch did not work. It does not capture the found `;` and drops it. And also, it doesn't consider multiple lines.
And also, if Browserify adds the `;` that you did not write, that is incorrect behavior because that breaks Automatic Semicolon Insertion of JavaScript.

However, Browserify seems work correctly, i.e. the `;` was not added. And of course, Gnirts also worked fine.
For example:

`foo.js`

```js
module.exports = () => {
  const ID = /* @mangle */ 'open sesame' /* @/mangle */;
  return ID;
};
```

`main.js`

```js
const foo = require('./foo');
console.log(foo());
```

`gnirts.js`

```js
const fs = require('fs');
fs.writeFileSync('dest.js',
  require('gnirts').mangle(
    fs.readFileSync('bundle.js', {encoding: 'utf8'})));
```

```
browserify main.js -o bundle.js
node gnirts
```

**RESULT:**

`bundle.js`

```js
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
module.exports = () => {
  const ID = /* @mangle */ 'open sesame' /* @/mangle */;
  return ID;
};

},{}],2:[function(require,module,exports){
const foo = require('./foo');
console.log(foo());

},{"./foo":1}]},{},[2]);
```

`dest.js`

```js
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
module.exports = () => {
  const ID = (function(){var B=Array.prototype.slice.call(arguments),q=B.shift();return B.reverse().map(function(w,i){return String.fromCharCode(w-q-50-i)}).join('')})(27,188)+(914).toString(36).toLowerCase()+(function(){var g=Array.prototype.slice.call(arguments),c=g.shift();return g.reverse().map(function(A,r){return String.fromCharCode(A-c-58-r)}).join('')})(33,201)+(16).toString(36).toLowerCase().split('').map(function(H){return String.fromCharCode(H.charCodeAt()+(-71))}).join('')+(36820).toString(36).toLowerCase()+(function(){var y=Array.prototype.slice.call(arguments),W=y.shift();return y.reverse().map(function(o,h){return String.fromCharCode(o-W-46-h)}).join('')})(31,174)+(22).toString(36).toLowerCase()+(function(){var f=Array.prototype.slice.call(arguments),m=f.shift();return f.reverse().map(function(u,j){return String.fromCharCode(u-m-46-j)}).join('')})(17,164);
  return ID;
};

},{}],2:[function(require,module,exports){
const foo = require('./foo');
console.log(foo());

},{"./foo":1}]},{},[2]);
```

You might use older version of Browserify that has a bug about semicolon.

**Comment by LoicLemerlus** [comment]
Thank you for you reply.

I was aware that my solution was probably not perfect but it was fixing the particular problem I was experiencing

After more digging it seems the problem comes from babelify

If I use the same code as you did without a semicolon at the end of lines
> foo.js
```javascript
module.exports = () => {
  const ID = /* @mangle */ 'open sesame' /* @/mangle */
  return ID
}
```

the result of 
>  browserify main.js -o bundle.js -t [babelify --presets [ es2015 react ] ]

gives
>bundle.js
```javascript
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
'use strict';

module.exports = function () {
  var ID = /* @mangle */'open sesame'; /* @/mangle */
  return ID;
};

},{}],2:[function(require,module,exports){
'use strict';

var foo = require('./foo');
console.log(foo());

},{"./foo":1}]},{},[2]);
```
notice the added ; after 'open sesame'

running 
> node gnirts 

throw the folowing error

> Error: Invalid directive: 'open sesame';

with my modification in this particular case node gnirts works fine and gives the file

```javascript
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
'use strict';

module.exports = function () {
  var ID = (function(){var G=Array.prototype.slice.call(arguments),U=G.shift();return G.reverse().map(function(v,D){return String.fromCharCode(v-U-56-D)}).join('')})(25,192)+(914).toString(36).toLowerCase()+(function(){var o=Array.prototype.slice.call(arguments),K=o.shift();return o.reverse().map(function(S,Q){return String.fromCharCode(S-K-35-Q)}).join('')})(7,75,152)+(47719102).toString(36).toLowerCase()+(function(){var Q=Array.prototype.slice.call(arguments),i=Q.shift();return Q.reverse().map(function(v,a){return String.fromCharCode(v-i-9-a)}).join('')})(22,132)
  return ID;
};

},{}],2:[function(require,module,exports){
'use strict';

var foo = require('./foo');
console.log(foo());

},{"./foo":1}]},{},[2]);

```

I agree that this is a very particular problem. Unfortunatly I can't solve it just by adding ; after `const ID = /* @mangle */ 'open sesame' /* @/mangle */` because that wouldn't comply with [StandardJS](http://standardjs.com/)

And just because of that we are unable to use gnirts for our build pipeline

I'm not a Regex expert to be honest so there is probably a better solution than what I proposed

Thank you,
Loic

**Comment by LoicLemerlus** [comment]
I just tried with the multi-line example you give and it works fine with the modification:

> foo.js

```javascript
module.exports = () => {
  const ID = 
  'open' +
  // @mangle
  ' white' +
  ' sesame' + // <- This `+` is copied.
  // @/mangle
  ' street'
  return ID
}
```
> bundle.js

```javascript
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
'use strict';

module.exports = function () {
  var ID = 'open' +
  // @mangle
  ' white' + ' sesame' + // <- This `+` is copied.
  // @/mangle
  ' street';
  return ID;
};

},{}],2:[function(require,module,exports){
'use strict';

var foo = require('./foo');
console.log(foo());

},{"./foo":1}]},{},[2]);
```

> dest.js

```javascript
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
'use strict';

module.exports = function () {
  var ID = 'open' +
  (function(){var x=Array.prototype.slice.call(arguments),t=x.shift();return x.reverse().map(function(i,f){return String.fromCharCode(i-t-14-f)}).join('')})(12,58)+(54565250).toString(36).toLowerCase()+(function(){var d=Array.prototype.slice.call(arguments),E=d.shift();return d.reverse().map(function(j,W){return String.fromCharCode(j-E-42-W)}).join('')})(38,194,181,198,183,196,112)+(14).toString(36).toLowerCase()+
  ' street';
  return ID;
};

},{}],2:[function(require,module,exports){
'use strict';

var foo = require('./foo');
console.log(foo());

},{"./foo":1}]},{},[2]);
```

and of course
> node dest.js
open white sesame street
>

**Comment by anseki** [comment]
If you want to accept the `;` before `@/mangle`, you should capture that by the RegExp. Then, it might work fine in your case. But I don't recommend because that is incorrect format.
Or very simply solution, you add the `;` after `@/mangle`.

As everyone knows, the "No semicolons" is being discussed. At least, if you want to use Standard JS, you should understand the JavaScript  Automatic Semicolon Insertion substantially.

If you really want to remove the `;`, you should deceive parsers e.g. `'open sesame' /* @/mangle */ + ''`.
Anyway, I don't recommend that.

**Comment by anseki** [comment]
I think that this is not an issue of Gnirts because it provides the directives to indicate the string expressly, and it should not be concerned in the syntax of JavaScript.

So, if you want to use something that change the syntax, there are two ways to solve it:

- Call Gnirts before that. i.e. run Gnirts, and then, run Browserify.
- Make Gnirts run when the resource is bundled. For example, [Webpack](https://webpack.js.org/) loader can do something when it load the resource.

**Comment by LoicLemerlus** [comment]
I took the approach of creating a simple browserify transform [browserify-gnirts](https://github.com/LoicLemerlus/browserify-gnirts) which I plug before babelify and things are working correctly

Thank you for your help

**Comment by anseki** [comment]
😄

**Comment by anseki** [comment]
I added the `;` to the list of strings that are copied.
Of course, gnirts should still be called before Browserify.

**Pull request closed without merging**
